source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'puma'
gem 'launchy'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'foundation-rails'
# gem 'redcarpet'
gem 'omniauth-github'
gem 'devise'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
end

group :development do
  gem 'web-console'
  gem 'spring'
end
